# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.2.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.2.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/aldor/workspace/atabox-server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/aldor/workspace/atabox-server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.2.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.2.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.2.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.2.3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.2.3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.2.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aldor/workspace/atabox-server/CMakeFiles /Users/aldor/workspace/atabox-server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aldor/workspace/atabox-server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named atabox_server

# Build rule for target.
atabox_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 atabox_server
.PHONY : atabox_server

# fast build rule for target.
atabox_server/fast:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/build
.PHONY : atabox_server/fast

#=============================================================================
# Target rules for targets named Aquila

# Build rule for target.
Aquila: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Aquila
.PHONY : Aquila

# fast build rule for target.
Aquila/fast:
	$(MAKE) -f external/aquila/CMakeFiles/Aquila.dir/build.make external/aquila/CMakeFiles/Aquila.dir/build
.PHONY : Aquila/fast

#=============================================================================
# Target rules for targets named examples

# Build rule for target.
examples: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples
.PHONY : examples

# fast build rule for target.
examples/fast:
	$(MAKE) -f external/aquila/CMakeFiles/examples.dir/build.make external/aquila/CMakeFiles/examples.dir/build
.PHONY : examples/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f external/aquila/CMakeFiles/uninstall.dir/build.make external/aquila/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named Kiss_fft

# Build rule for target.
Kiss_fft: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Kiss_fft
.PHONY : Kiss_fft

# fast build rule for target.
Kiss_fft/fast:
	$(MAKE) -f external/aquila/lib/CMakeFiles/Kiss_fft.dir/build.make external/aquila/lib/CMakeFiles/Kiss_fft.dir/build
.PHONY : Kiss_fft/fast

#=============================================================================
# Target rules for targets named Ooura_fft

# Build rule for target.
Ooura_fft: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Ooura_fft
.PHONY : Ooura_fft

# fast build rule for target.
Ooura_fft/fast:
	$(MAKE) -f external/aquila/lib/CMakeFiles/Ooura_fft.dir/build.make external/aquila/lib/CMakeFiles/Ooura_fft.dir/build
.PHONY : Ooura_fft/fast

#=============================================================================
# Target rules for targets named TestUnitTest++

# Build rule for target.
TestUnitTest++: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestUnitTest++
.PHONY : TestUnitTest++

# fast build rule for target.
TestUnitTest++/fast:
	$(MAKE) -f external/aquila/lib/unittestpp/CMakeFiles/TestUnitTest++.dir/build.make external/aquila/lib/unittestpp/CMakeFiles/TestUnitTest++.dir/build
.PHONY : TestUnitTest++/fast

#=============================================================================
# Target rules for targets named UnitTest++

# Build rule for target.
UnitTest++: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UnitTest++
.PHONY : UnitTest++

# fast build rule for target.
UnitTest++/fast:
	$(MAKE) -f external/aquila/lib/unittestpp/CMakeFiles/UnitTest++.dir/build.make external/aquila/lib/unittestpp/CMakeFiles/UnitTest++.dir/build
.PHONY : UnitTest++/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f external/aquila/lib/unittestpp/CMakeFiles/check.dir/build.make external/aquila/lib/unittestpp/CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named utility_functions

# Build rule for target.
utility_functions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utility_functions
.PHONY : utility_functions

# fast build rule for target.
utility_functions/fast:
	$(MAKE) -f external/aquila/examples/utility_functions/CMakeFiles/utility_functions.dir/build.make external/aquila/examples/utility_functions/CMakeFiles/utility_functions.dir/build
.PHONY : utility_functions/fast

#=============================================================================
# Target rules for targets named frame_iteration

# Build rule for target.
frame_iteration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 frame_iteration
.PHONY : frame_iteration

# fast build rule for target.
frame_iteration/fast:
	$(MAKE) -f external/aquila/examples/frame_iteration/CMakeFiles/frame_iteration.dir/build.make external/aquila/examples/frame_iteration/CMakeFiles/frame_iteration.dir/build
.PHONY : frame_iteration/fast

#=============================================================================
# Target rules for targets named wave_info

# Build rule for target.
wave_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wave_info
.PHONY : wave_info

# fast build rule for target.
wave_info/fast:
	$(MAKE) -f external/aquila/examples/wave_info/CMakeFiles/wave_info.dir/build.make external/aquila/examples/wave_info/CMakeFiles/wave_info.dir/build
.PHONY : wave_info/fast

#=============================================================================
# Target rules for targets named wave_mfcc

# Build rule for target.
wave_mfcc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wave_mfcc
.PHONY : wave_mfcc

# fast build rule for target.
wave_mfcc/fast:
	$(MAKE) -f external/aquila/examples/wave_mfcc/CMakeFiles/wave_mfcc.dir/build.make external/aquila/examples/wave_mfcc/CMakeFiles/wave_mfcc.dir/build
.PHONY : wave_mfcc/fast

#=============================================================================
# Target rules for targets named wave_iteration

# Build rule for target.
wave_iteration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wave_iteration
.PHONY : wave_iteration

# fast build rule for target.
wave_iteration/fast:
	$(MAKE) -f external/aquila/examples/wave_iteration/CMakeFiles/wave_iteration.dir/build.make external/aquila/examples/wave_iteration/CMakeFiles/wave_iteration.dir/build
.PHONY : wave_iteration/fast

#=============================================================================
# Target rules for targets named window_plot

# Build rule for target.
window_plot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 window_plot
.PHONY : window_plot

# fast build rule for target.
window_plot/fast:
	$(MAKE) -f external/aquila/examples/window_plot/CMakeFiles/window_plot.dir/build.make external/aquila/examples/window_plot/CMakeFiles/window_plot.dir/build
.PHONY : window_plot/fast

#=============================================================================
# Target rules for targets named window_usage

# Build rule for target.
window_usage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 window_usage
.PHONY : window_usage

# fast build rule for target.
window_usage/fast:
	$(MAKE) -f external/aquila/examples/window_usage/CMakeFiles/window_usage.dir/build.make external/aquila/examples/window_usage/CMakeFiles/window_usage.dir/build
.PHONY : window_usage/fast

#=============================================================================
# Target rules for targets named text_plot

# Build rule for target.
text_plot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 text_plot
.PHONY : text_plot

# fast build rule for target.
text_plot/fast:
	$(MAKE) -f external/aquila/examples/text_plot/CMakeFiles/text_plot.dir/build.make external/aquila/examples/text_plot/CMakeFiles/text_plot.dir/build
.PHONY : text_plot/fast

#=============================================================================
# Target rules for targets named sine_generator

# Build rule for target.
sine_generator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sine_generator
.PHONY : sine_generator

# fast build rule for target.
sine_generator/fast:
	$(MAKE) -f external/aquila/examples/sine_generator/CMakeFiles/sine_generator.dir/build.make external/aquila/examples/sine_generator/CMakeFiles/sine_generator.dir/build
.PHONY : sine_generator/fast

#=============================================================================
# Target rules for targets named square_generator

# Build rule for target.
square_generator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 square_generator
.PHONY : square_generator

# fast build rule for target.
square_generator/fast:
	$(MAKE) -f external/aquila/examples/square_generator/CMakeFiles/square_generator.dir/build.make external/aquila/examples/square_generator/CMakeFiles/square_generator.dir/build
.PHONY : square_generator/fast

#=============================================================================
# Target rules for targets named triangle_generator

# Build rule for target.
triangle_generator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangle_generator
.PHONY : triangle_generator

# fast build rule for target.
triangle_generator/fast:
	$(MAKE) -f external/aquila/examples/triangle_generator/CMakeFiles/triangle_generator.dir/build.make external/aquila/examples/triangle_generator/CMakeFiles/triangle_generator.dir/build
.PHONY : triangle_generator/fast

#=============================================================================
# Target rules for targets named generators

# Build rule for target.
generators: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generators
.PHONY : generators

# fast build rule for target.
generators/fast:
	$(MAKE) -f external/aquila/examples/generators/CMakeFiles/generators.dir/build.make external/aquila/examples/generators/CMakeFiles/generators.dir/build
.PHONY : generators/fast

#=============================================================================
# Target rules for targets named am_modulation

# Build rule for target.
am_modulation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 am_modulation
.PHONY : am_modulation

# fast build rule for target.
am_modulation/fast:
	$(MAKE) -f external/aquila/examples/am_modulation/CMakeFiles/am_modulation.dir/build.make external/aquila/examples/am_modulation/CMakeFiles/am_modulation.dir/build
.PHONY : am_modulation/fast

#=============================================================================
# Target rules for targets named fft_comparison

# Build rule for target.
fft_comparison: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fft_comparison
.PHONY : fft_comparison

# fast build rule for target.
fft_comparison/fast:
	$(MAKE) -f external/aquila/examples/fft_comparison/CMakeFiles/fft_comparison.dir/build.make external/aquila/examples/fft_comparison/CMakeFiles/fft_comparison.dir/build
.PHONY : fft_comparison/fast

#=============================================================================
# Target rules for targets named fft_simple_spectrum

# Build rule for target.
fft_simple_spectrum: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fft_simple_spectrum
.PHONY : fft_simple_spectrum

# fast build rule for target.
fft_simple_spectrum/fast:
	$(MAKE) -f external/aquila/examples/fft_simple_spectrum/CMakeFiles/fft_simple_spectrum.dir/build.make external/aquila/examples/fft_simple_spectrum/CMakeFiles/fft_simple_spectrum.dir/build
.PHONY : fft_simple_spectrum/fast

#=============================================================================
# Target rules for targets named fft_filter

# Build rule for target.
fft_filter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fft_filter
.PHONY : fft_filter

# fast build rule for target.
fft_filter/fast:
	$(MAKE) -f external/aquila/examples/fft_filter/CMakeFiles/fft_filter.dir/build.make external/aquila/examples/fft_filter/CMakeFiles/fft_filter.dir/build
.PHONY : fft_filter/fast

#=============================================================================
# Target rules for targets named spectrogram

# Build rule for target.
spectrogram: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spectrogram
.PHONY : spectrogram

# fast build rule for target.
spectrogram/fast:
	$(MAKE) -f external/aquila/examples/spectrogram/CMakeFiles/spectrogram.dir/build.make external/aquila/examples/spectrogram/CMakeFiles/spectrogram.dir/build
.PHONY : spectrogram/fast

#=============================================================================
# Target rules for targets named mfcc_calculation

# Build rule for target.
mfcc_calculation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mfcc_calculation
.PHONY : mfcc_calculation

# fast build rule for target.
mfcc_calculation/fast:
	$(MAKE) -f external/aquila/examples/mfcc_calculation/CMakeFiles/mfcc_calculation.dir/build.make external/aquila/examples/mfcc_calculation/CMakeFiles/mfcc_calculation.dir/build
.PHONY : mfcc_calculation/fast

#=============================================================================
# Target rules for targets named dtw_path_recovery

# Build rule for target.
dtw_path_recovery: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dtw_path_recovery
.PHONY : dtw_path_recovery

# fast build rule for target.
dtw_path_recovery/fast:
	$(MAKE) -f external/aquila/examples/dtw_path_recovery/CMakeFiles/dtw_path_recovery.dir/build.make external/aquila/examples/dtw_path_recovery/CMakeFiles/dtw_path_recovery.dir/build
.PHONY : dtw_path_recovery/fast

#=============================================================================
# Target rules for targets named aquila_test

# Build rule for target.
aquila_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aquila_test
.PHONY : aquila_test

# fast build rule for target.
aquila_test/fast:
	$(MAKE) -f external/aquila/tests/CMakeFiles/aquila_test.dir/build.make external/aquila/tests/CMakeFiles/aquila_test.dir/build
.PHONY : aquila_test/fast

#=============================================================================
# Target rules for targets named cpprest

# Build rule for target.
cpprest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpprest
.PHONY : cpprest

# fast build rule for target.
cpprest/fast:
	$(MAKE) -f external/casablanca/Release/src/CMakeFiles/cpprest.dir/build.make external/casablanca/Release/src/CMakeFiles/cpprest.dir/build
.PHONY : cpprest/fast

#=============================================================================
# Target rules for targets named common_utilities

# Build rule for target.
common_utilities: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 common_utilities
.PHONY : common_utilities

# fast build rule for target.
common_utilities/fast:
	$(MAKE) -f external/casablanca/Release/tests/common/utilities/CMakeFiles/common_utilities.dir/build.make external/casablanca/Release/tests/common/utilities/CMakeFiles/common_utilities.dir/build
.PHONY : common_utilities/fast

#=============================================================================
# Target rules for targets named unittestpp

# Build rule for target.
unittestpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittestpp
.PHONY : unittestpp

# fast build rule for target.
unittestpp/fast:
	$(MAKE) -f external/casablanca/Release/tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/build.make external/casablanca/Release/tests/common/UnitTestpp/CMakeFiles/unittestpp.dir/build
.PHONY : unittestpp/fast

#=============================================================================
# Target rules for targets named test_runner

# Build rule for target.
test_runner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_runner
.PHONY : test_runner

# fast build rule for target.
test_runner/fast:
	$(MAKE) -f external/casablanca/Release/tests/common/TestRunner/CMakeFiles/test_runner.dir/build.make external/casablanca/Release/tests/common/TestRunner/CMakeFiles/test_runner.dir/build
.PHONY : test_runner/fast

#=============================================================================
# Target rules for targets named httptest_utilities

# Build rule for target.
httptest_utilities: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 httptest_utilities
.PHONY : httptest_utilities

# fast build rule for target.
httptest_utilities/fast:
	$(MAKE) -f external/casablanca/Release/tests/functional/http/utilities/CMakeFiles/httptest_utilities.dir/build.make external/casablanca/Release/tests/functional/http/utilities/CMakeFiles/httptest_utilities.dir/build
.PHONY : httptest_utilities/fast

#=============================================================================
# Target rules for targets named httpclient_test

# Build rule for target.
httpclient_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 httpclient_test
.PHONY : httpclient_test

# fast build rule for target.
httpclient_test/fast:
	$(MAKE) -f external/casablanca/Release/tests/functional/http/client/CMakeFiles/httpclient_test.dir/build.make external/casablanca/Release/tests/functional/http/client/CMakeFiles/httpclient_test.dir/build
.PHONY : httpclient_test/fast

#=============================================================================
# Target rules for targets named httplistener_test

# Build rule for target.
httplistener_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 httplistener_test
.PHONY : httplistener_test

# fast build rule for target.
httplistener_test/fast:
	$(MAKE) -f external/casablanca/Release/tests/functional/http/listener/CMakeFiles/httplistener_test.dir/build.make external/casablanca/Release/tests/functional/http/listener/CMakeFiles/httplistener_test.dir/build
.PHONY : httplistener_test/fast

#=============================================================================
# Target rules for targets named json_test

# Build rule for target.
json_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 json_test
.PHONY : json_test

# fast build rule for target.
json_test/fast:
	$(MAKE) -f external/casablanca/Release/tests/functional/json/CMakeFiles/json_test.dir/build.make external/casablanca/Release/tests/functional/json/CMakeFiles/json_test.dir/build
.PHONY : json_test/fast

#=============================================================================
# Target rules for targets named pplx_test

# Build rule for target.
pplx_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pplx_test
.PHONY : pplx_test

# fast build rule for target.
pplx_test/fast:
	$(MAKE) -f external/casablanca/Release/tests/functional/pplx/pplx_test/CMakeFiles/pplx_test.dir/build.make external/casablanca/Release/tests/functional/pplx/pplx_test/CMakeFiles/pplx_test.dir/build
.PHONY : pplx_test/fast

#=============================================================================
# Target rules for targets named streams_test

# Build rule for target.
streams_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 streams_test
.PHONY : streams_test

# fast build rule for target.
streams_test/fast:
	$(MAKE) -f external/casablanca/Release/tests/functional/streams/CMakeFiles/streams_test.dir/build.make external/casablanca/Release/tests/functional/streams/CMakeFiles/streams_test.dir/build
.PHONY : streams_test/fast

#=============================================================================
# Target rules for targets named uri_test

# Build rule for target.
uri_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uri_test
.PHONY : uri_test

# fast build rule for target.
uri_test/fast:
	$(MAKE) -f external/casablanca/Release/tests/functional/uri/CMakeFiles/uri_test.dir/build.make external/casablanca/Release/tests/functional/uri/CMakeFiles/uri_test.dir/build
.PHONY : uri_test/fast

#=============================================================================
# Target rules for targets named utils_test

# Build rule for target.
utils_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils_test
.PHONY : utils_test

# fast build rule for target.
utils_test/fast:
	$(MAKE) -f external/casablanca/Release/tests/functional/utils/CMakeFiles/utils_test.dir/build.make external/casablanca/Release/tests/functional/utils/CMakeFiles/utils_test.dir/build
.PHONY : utils_test/fast

#=============================================================================
# Target rules for targets named websocketclient_test

# Build rule for target.
websocketclient_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 websocketclient_test
.PHONY : websocketclient_test

# fast build rule for target.
websocketclient_test/fast:
	$(MAKE) -f external/casablanca/Release/tests/functional/websockets/client/CMakeFiles/websocketclient_test.dir/build.make external/casablanca/Release/tests/functional/websockets/client/CMakeFiles/websocketclient_test.dir/build
.PHONY : websocketclient_test/fast

#=============================================================================
# Target rules for targets named websockettest_utilities

# Build rule for target.
websockettest_utilities: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 websockettest_utilities
.PHONY : websockettest_utilities

# fast build rule for target.
websockettest_utilities/fast:
	$(MAKE) -f external/casablanca/Release/tests/functional/websockets/utilities/CMakeFiles/websockettest_utilities.dir/build.make external/casablanca/Release/tests/functional/websockets/utilities/CMakeFiles/websockettest_utilities.dir/build
.PHONY : websockettest_utilities/fast

#=============================================================================
# Target rules for targets named samples

# Build rule for target.
samples: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 samples
.PHONY : samples

# fast build rule for target.
samples/fast:
	$(MAKE) -f external/casablanca/Release/samples/CMakeFiles/samples.dir/build.make external/casablanca/Release/samples/CMakeFiles/samples.dir/build
.PHONY : samples/fast

#=============================================================================
# Target rules for targets named SearchFile

# Build rule for target.
SearchFile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SearchFile
.PHONY : SearchFile

# fast build rule for target.
SearchFile/fast:
	$(MAKE) -f external/casablanca/Release/samples/SearchFile/CMakeFiles/SearchFile.dir/build.make external/casablanca/Release/samples/SearchFile/CMakeFiles/SearchFile.dir/build
.PHONY : SearchFile/fast

#=============================================================================
# Target rules for targets named BingRequest

# Build rule for target.
BingRequest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BingRequest
.PHONY : BingRequest

# fast build rule for target.
BingRequest/fast:
	$(MAKE) -f external/casablanca/Release/samples/BingRequest/CMakeFiles/BingRequest.dir/build.make external/casablanca/Release/samples/BingRequest/CMakeFiles/BingRequest.dir/build
.PHONY : BingRequest/fast

#=============================================================================
# Target rules for targets named blackjackserver

# Build rule for target.
blackjackserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blackjackserver
.PHONY : blackjackserver

# fast build rule for target.
blackjackserver/fast:
	$(MAKE) -f external/casablanca/Release/samples/BlackJack/BlackJack_Server/CMakeFiles/blackjackserver.dir/build.make external/casablanca/Release/samples/BlackJack/BlackJack_Server/CMakeFiles/blackjackserver.dir/build
.PHONY : blackjackserver/fast

#=============================================================================
# Target rules for targets named blackjackclient

# Build rule for target.
blackjackclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blackjackclient
.PHONY : blackjackclient

# fast build rule for target.
blackjackclient/fast:
	$(MAKE) -f external/casablanca/Release/samples/BlackJack/BlackJack_Client/CMakeFiles/blackjackclient.dir/build.make external/casablanca/Release/samples/BlackJack/BlackJack_Client/CMakeFiles/blackjackclient.dir/build
.PHONY : blackjackclient/fast

#=============================================================================
# Target rules for targets named oauth1client

# Build rule for target.
oauth1client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oauth1client
.PHONY : oauth1client

# fast build rule for target.
oauth1client/fast:
	$(MAKE) -f external/casablanca/Release/samples/Oauth1Client/CMakeFiles/oauth1client.dir/build.make external/casablanca/Release/samples/Oauth1Client/CMakeFiles/oauth1client.dir/build
.PHONY : oauth1client/fast

#=============================================================================
# Target rules for targets named oauth2client

# Build rule for target.
oauth2client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oauth2client
.PHONY : oauth2client

# fast build rule for target.
oauth2client/fast:
	$(MAKE) -f external/casablanca/Release/samples/Oauth2Client/CMakeFiles/oauth2client.dir/build.make external/casablanca/Release/samples/Oauth2Client/CMakeFiles/oauth2client.dir/build
.PHONY : oauth2client/fast

src/api/AtaboxApi.o: src/api/AtaboxApi.cpp.o
.PHONY : src/api/AtaboxApi.o

# target to build an object file
src/api/AtaboxApi.cpp.o:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/api/AtaboxApi.cpp.o
.PHONY : src/api/AtaboxApi.cpp.o

src/api/AtaboxApi.i: src/api/AtaboxApi.cpp.i
.PHONY : src/api/AtaboxApi.i

# target to preprocess a source file
src/api/AtaboxApi.cpp.i:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/api/AtaboxApi.cpp.i
.PHONY : src/api/AtaboxApi.cpp.i

src/api/AtaboxApi.s: src/api/AtaboxApi.cpp.s
.PHONY : src/api/AtaboxApi.s

# target to generate assembly for a file
src/api/AtaboxApi.cpp.s:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/api/AtaboxApi.cpp.s
.PHONY : src/api/AtaboxApi.cpp.s

src/dataproviders/FileDataProvider.o: src/dataproviders/FileDataProvider.cpp.o
.PHONY : src/dataproviders/FileDataProvider.o

# target to build an object file
src/dataproviders/FileDataProvider.cpp.o:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/dataproviders/FileDataProvider.cpp.o
.PHONY : src/dataproviders/FileDataProvider.cpp.o

src/dataproviders/FileDataProvider.i: src/dataproviders/FileDataProvider.cpp.i
.PHONY : src/dataproviders/FileDataProvider.i

# target to preprocess a source file
src/dataproviders/FileDataProvider.cpp.i:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/dataproviders/FileDataProvider.cpp.i
.PHONY : src/dataproviders/FileDataProvider.cpp.i

src/dataproviders/FileDataProvider.s: src/dataproviders/FileDataProvider.cpp.s
.PHONY : src/dataproviders/FileDataProvider.s

# target to generate assembly for a file
src/dataproviders/FileDataProvider.cpp.s:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/dataproviders/FileDataProvider.cpp.s
.PHONY : src/dataproviders/FileDataProvider.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/recognition/ProcessAndAnalyze.o: src/recognition/ProcessAndAnalyze.cpp.o
.PHONY : src/recognition/ProcessAndAnalyze.o

# target to build an object file
src/recognition/ProcessAndAnalyze.cpp.o:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/recognition/ProcessAndAnalyze.cpp.o
.PHONY : src/recognition/ProcessAndAnalyze.cpp.o

src/recognition/ProcessAndAnalyze.i: src/recognition/ProcessAndAnalyze.cpp.i
.PHONY : src/recognition/ProcessAndAnalyze.i

# target to preprocess a source file
src/recognition/ProcessAndAnalyze.cpp.i:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/recognition/ProcessAndAnalyze.cpp.i
.PHONY : src/recognition/ProcessAndAnalyze.cpp.i

src/recognition/ProcessAndAnalyze.s: src/recognition/ProcessAndAnalyze.cpp.s
.PHONY : src/recognition/ProcessAndAnalyze.s

# target to generate assembly for a file
src/recognition/ProcessAndAnalyze.cpp.s:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/recognition/ProcessAndAnalyze.cpp.s
.PHONY : src/recognition/ProcessAndAnalyze.cpp.s

src/recognition/PropertiesComparator.o: src/recognition/PropertiesComparator.cpp.o
.PHONY : src/recognition/PropertiesComparator.o

# target to build an object file
src/recognition/PropertiesComparator.cpp.o:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/recognition/PropertiesComparator.cpp.o
.PHONY : src/recognition/PropertiesComparator.cpp.o

src/recognition/PropertiesComparator.i: src/recognition/PropertiesComparator.cpp.i
.PHONY : src/recognition/PropertiesComparator.i

# target to preprocess a source file
src/recognition/PropertiesComparator.cpp.i:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/recognition/PropertiesComparator.cpp.i
.PHONY : src/recognition/PropertiesComparator.cpp.i

src/recognition/PropertiesComparator.s: src/recognition/PropertiesComparator.cpp.s
.PHONY : src/recognition/PropertiesComparator.s

# target to generate assembly for a file
src/recognition/PropertiesComparator.cpp.s:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/recognition/PropertiesComparator.cpp.s
.PHONY : src/recognition/PropertiesComparator.cpp.s

src/runner/Runner.o: src/runner/Runner.cpp.o
.PHONY : src/runner/Runner.o

# target to build an object file
src/runner/Runner.cpp.o:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/runner/Runner.cpp.o
.PHONY : src/runner/Runner.cpp.o

src/runner/Runner.i: src/runner/Runner.cpp.i
.PHONY : src/runner/Runner.i

# target to preprocess a source file
src/runner/Runner.cpp.i:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/runner/Runner.cpp.i
.PHONY : src/runner/Runner.cpp.i

src/runner/Runner.s: src/runner/Runner.cpp.s
.PHONY : src/runner/Runner.s

# target to generate assembly for a file
src/runner/Runner.cpp.s:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/runner/Runner.cpp.s
.PHONY : src/runner/Runner.cpp.s

src/utils/atabox_log.o: src/utils/atabox_log.cpp.o
.PHONY : src/utils/atabox_log.o

# target to build an object file
src/utils/atabox_log.cpp.o:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/utils/atabox_log.cpp.o
.PHONY : src/utils/atabox_log.cpp.o

src/utils/atabox_log.i: src/utils/atabox_log.cpp.i
.PHONY : src/utils/atabox_log.i

# target to preprocess a source file
src/utils/atabox_log.cpp.i:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/utils/atabox_log.cpp.i
.PHONY : src/utils/atabox_log.cpp.i

src/utils/atabox_log.s: src/utils/atabox_log.cpp.s
.PHONY : src/utils/atabox_log.s

# target to generate assembly for a file
src/utils/atabox_log.cpp.s:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/utils/atabox_log.cpp.s
.PHONY : src/utils/atabox_log.cpp.s

src/wave/Samples.o: src/wave/Samples.cpp.o
.PHONY : src/wave/Samples.o

# target to build an object file
src/wave/Samples.cpp.o:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/wave/Samples.cpp.o
.PHONY : src/wave/Samples.cpp.o

src/wave/Samples.i: src/wave/Samples.cpp.i
.PHONY : src/wave/Samples.i

# target to preprocess a source file
src/wave/Samples.cpp.i:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/wave/Samples.cpp.i
.PHONY : src/wave/Samples.cpp.i

src/wave/Samples.s: src/wave/Samples.cpp.s
.PHONY : src/wave/Samples.s

# target to generate assembly for a file
src/wave/Samples.cpp.s:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/wave/Samples.cpp.s
.PHONY : src/wave/Samples.cpp.s

src/wave/WaveFile.o: src/wave/WaveFile.cpp.o
.PHONY : src/wave/WaveFile.o

# target to build an object file
src/wave/WaveFile.cpp.o:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/wave/WaveFile.cpp.o
.PHONY : src/wave/WaveFile.cpp.o

src/wave/WaveFile.i: src/wave/WaveFile.cpp.i
.PHONY : src/wave/WaveFile.i

# target to preprocess a source file
src/wave/WaveFile.cpp.i:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/wave/WaveFile.cpp.i
.PHONY : src/wave/WaveFile.cpp.i

src/wave/WaveFile.s: src/wave/WaveFile.cpp.s
.PHONY : src/wave/WaveFile.s

# target to generate assembly for a file
src/wave/WaveFile.cpp.s:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/wave/WaveFile.cpp.s
.PHONY : src/wave/WaveFile.cpp.s

src/wave/WaveUtils.o: src/wave/WaveUtils.cpp.o
.PHONY : src/wave/WaveUtils.o

# target to build an object file
src/wave/WaveUtils.cpp.o:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/wave/WaveUtils.cpp.o
.PHONY : src/wave/WaveUtils.cpp.o

src/wave/WaveUtils.i: src/wave/WaveUtils.cpp.i
.PHONY : src/wave/WaveUtils.i

# target to preprocess a source file
src/wave/WaveUtils.cpp.i:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/wave/WaveUtils.cpp.i
.PHONY : src/wave/WaveUtils.cpp.i

src/wave/WaveUtils.s: src/wave/WaveUtils.cpp.s
.PHONY : src/wave/WaveUtils.s

# target to generate assembly for a file
src/wave/WaveUtils.cpp.s:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/wave/WaveUtils.cpp.s
.PHONY : src/wave/WaveUtils.cpp.s

src/wave/analysis/SamplesAnalizator.o: src/wave/analysis/SamplesAnalizator.cpp.o
.PHONY : src/wave/analysis/SamplesAnalizator.o

# target to build an object file
src/wave/analysis/SamplesAnalizator.cpp.o:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/wave/analysis/SamplesAnalizator.cpp.o
.PHONY : src/wave/analysis/SamplesAnalizator.cpp.o

src/wave/analysis/SamplesAnalizator.i: src/wave/analysis/SamplesAnalizator.cpp.i
.PHONY : src/wave/analysis/SamplesAnalizator.i

# target to preprocess a source file
src/wave/analysis/SamplesAnalizator.cpp.i:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/wave/analysis/SamplesAnalizator.cpp.i
.PHONY : src/wave/analysis/SamplesAnalizator.cpp.i

src/wave/analysis/SamplesAnalizator.s: src/wave/analysis/SamplesAnalizator.cpp.s
.PHONY : src/wave/analysis/SamplesAnalizator.s

# target to generate assembly for a file
src/wave/analysis/SamplesAnalizator.cpp.s:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/wave/analysis/SamplesAnalizator.cpp.s
.PHONY : src/wave/analysis/SamplesAnalizator.cpp.s

src/wave/processing/Processor.o: src/wave/processing/Processor.cpp.o
.PHONY : src/wave/processing/Processor.o

# target to build an object file
src/wave/processing/Processor.cpp.o:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/wave/processing/Processor.cpp.o
.PHONY : src/wave/processing/Processor.cpp.o

src/wave/processing/Processor.i: src/wave/processing/Processor.cpp.i
.PHONY : src/wave/processing/Processor.i

# target to preprocess a source file
src/wave/processing/Processor.cpp.i:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/wave/processing/Processor.cpp.i
.PHONY : src/wave/processing/Processor.cpp.i

src/wave/processing/Processor.s: src/wave/processing/Processor.cpp.s
.PHONY : src/wave/processing/Processor.s

# target to generate assembly for a file
src/wave/processing/Processor.cpp.s:
	$(MAKE) -f CMakeFiles/atabox_server.dir/build.make CMakeFiles/atabox_server.dir/src/wave/processing/Processor.cpp.s
.PHONY : src/wave/processing/Processor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... atabox_server"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... Aquila"
	@echo "... uninstall"
	@echo "... examples"
	@echo "... Ooura_fft"
	@echo "... Kiss_fft"
	@echo "... UnitTest++"
	@echo "... check"
	@echo "... TestUnitTest++"
	@echo "... utility_functions"
	@echo "... frame_iteration"
	@echo "... wave_info"
	@echo "... wave_mfcc"
	@echo "... wave_iteration"
	@echo "... window_plot"
	@echo "... window_usage"
	@echo "... text_plot"
	@echo "... sine_generator"
	@echo "... square_generator"
	@echo "... triangle_generator"
	@echo "... generators"
	@echo "... am_modulation"
	@echo "... fft_comparison"
	@echo "... fft_simple_spectrum"
	@echo "... fft_filter"
	@echo "... spectrogram"
	@echo "... mfcc_calculation"
	@echo "... dtw_path_recovery"
	@echo "... aquila_test"
	@echo "... cpprest"
	@echo "... common_utilities"
	@echo "... unittestpp"
	@echo "... test_runner"
	@echo "... httptest_utilities"
	@echo "... httpclient_test"
	@echo "... httplistener_test"
	@echo "... json_test"
	@echo "... pplx_test"
	@echo "... streams_test"
	@echo "... uri_test"
	@echo "... utils_test"
	@echo "... websocketclient_test"
	@echo "... websockettest_utilities"
	@echo "... samples"
	@echo "... SearchFile"
	@echo "... BingRequest"
	@echo "... blackjackserver"
	@echo "... blackjackclient"
	@echo "... oauth1client"
	@echo "... oauth2client"
	@echo "... src/api/AtaboxApi.o"
	@echo "... src/api/AtaboxApi.i"
	@echo "... src/api/AtaboxApi.s"
	@echo "... src/dataproviders/FileDataProvider.o"
	@echo "... src/dataproviders/FileDataProvider.i"
	@echo "... src/dataproviders/FileDataProvider.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/recognition/ProcessAndAnalyze.o"
	@echo "... src/recognition/ProcessAndAnalyze.i"
	@echo "... src/recognition/ProcessAndAnalyze.s"
	@echo "... src/recognition/PropertiesComparator.o"
	@echo "... src/recognition/PropertiesComparator.i"
	@echo "... src/recognition/PropertiesComparator.s"
	@echo "... src/runner/Runner.o"
	@echo "... src/runner/Runner.i"
	@echo "... src/runner/Runner.s"
	@echo "... src/utils/atabox_log.o"
	@echo "... src/utils/atabox_log.i"
	@echo "... src/utils/atabox_log.s"
	@echo "... src/wave/Samples.o"
	@echo "... src/wave/Samples.i"
	@echo "... src/wave/Samples.s"
	@echo "... src/wave/WaveFile.o"
	@echo "... src/wave/WaveFile.i"
	@echo "... src/wave/WaveFile.s"
	@echo "... src/wave/WaveUtils.o"
	@echo "... src/wave/WaveUtils.i"
	@echo "... src/wave/WaveUtils.s"
	@echo "... src/wave/analysis/SamplesAnalizator.o"
	@echo "... src/wave/analysis/SamplesAnalizator.i"
	@echo "... src/wave/analysis/SamplesAnalizator.s"
	@echo "... src/wave/processing/Processor.o"
	@echo "... src/wave/processing/Processor.i"
	@echo "... src/wave/processing/Processor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

